name: Run Notion Script

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  run-notion-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3 for Node.js 20 support

      - name: Set up Python
        uses: actions/setup-python@v4  # Update to v4 for Node.js 20 support
        with:
          python-version: '3.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: python create_notion_page.py
